FROM node:20-alpine

WORKDIR /app

COPY .npmrc package*.json ./
COPY frontend/package.json frontend/package.json
COPY backend/package.json backend/package.json
RUN npm ci

COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev", "--workspace=frontend", "--", "--host", "0.0.0.0"]
