FROM node:20-alpine

WORKDIR /app

COPY .npmrc package*.json ./
COPY frontend/package.json frontend/package.json
COPY backend/package.json backend/package.json
RUN npm ci

COPY . .

EXPOSE 3001

CMD ["npm", "run", "dev:docker", "--workspace=backend"]
