
import type { Resource, ScheduledItem } from "./types.ts";     

export const resources: Resource[] = [
  {
    key: "alex",
    name: "Alex Rivera",
    label: "Alex Rivera - Diagnostics and EV systems",
    description: "Diagnostics and EV systems",
  },
  {
    key: "nina",
    name: "Nina Patel",
    label: "Nina Patel - Brakes and suspension",
    description: "Brakes and suspension",
  },
  {
    key: "marek",
    name: "Marek Nowak",
    label: "Marek Nowak - Engine and drivetrain",
    description: "Engine and drivetrain",
  },
  {
    key: "sofia",
    name: "Sofia Chen",
    label: "Sofia Chen - Electrical and infotainment",
    description: "Electrical and infotainment",
  },
];

export const seedScheduledItems: ScheduledItem[] = [
  {
    id: 1,
    text: "EV range diagnostic",
    start_date: "2026-06-05 09:00",
    end_date: "2026-06-05 10:30",
    resource_id: "alex",
    requester: "Emma Thompson",
    location: "Bay 1",
    asset: "2024 Hyundai Ioniq 5",
    issue: "Range estimate drops after overnight charge",
    work_type: "EV diagnostic",
    status: "scheduled",
    priority: "urgent",
  },
  {
    id: 2,
    text: "Brake vibration inspection",
    start_date: "2026-06-05 09:30",
    end_date: "2026-06-05 11:00",
    resource_id: "nina",
    requester: "Daniel Brooks",
    location: "Bay 2",
    asset: "2021 Toyota RAV4",
    issue: "Steering wheel vibration under braking",
    work_type: "Brake inspection",
    status: "in_progress",
    priority: "normal",
  },
  {
    id: 3,
    text: "Oil leak and belt noise",
    start_date: "2026-06-05 09:00",
    end_date: "2026-06-05 11:30",
    resource_id: "marek",
    requester: "Olivia Martin",
    location: "Bay 3",
    asset: "2018 Ford Transit",
    issue: "Oil spots under engine and squeal on cold start",
    work_type: "Engine repair",
    status: "scheduled",
    priority: "normal",
  },
  {
    id: 4,
    text: "Infotainment reboot",
    start_date: "2026-06-05 10:00",
    end_date: "2026-06-05 11:30",
    resource_id: "sofia",
    requester: "Liam Chen",
    location: "Bay 4",
    asset: "2022 Volkswagen ID.4",
    issue: "Center screen reboots while using navigation",
    work_type: "Infotainment",
    status: "scheduled",
    priority: "normal",
  },
  {
    id: 5,
    text: "Suspension clunk",
    start_date: "2026-06-05 13:00",
    end_date: "2026-06-05 14:30",
    resource_id: "nina",
    requester: "Mia Gonzalez",
    location: "Bay 5",
    asset: "2020 Subaru Outback",
    issue: "Front-end clunk over speed bumps",
    work_type: "Suspension",
    status: "scheduled",
    priority: "normal",
  },
  {
    id: 6,
    text: "Transmission hesitation",
    start_date: "2026-06-05 13:00",
    end_date: "2026-06-05 15:30",
    resource_id: "marek",
    requester: "Noah Williams",
    location: "Bay 6",
    asset: "2019 BMW 330i",
    issue: "Hesitation shifting from second to third",
    work_type: "Drivetrain",
    status: "waiting_parts",
    priority: "urgent",
  },
  {
    id: 7,
    text: "Charging port fault",
    start_date: "2026-06-05 14:00",
    end_date: "2026-06-05 16:00",
    resource_id: "alex",
    requester: "Ava Johnson",
    location: "Bay 7",
    asset: "2023 Kia EV6",
    issue: "Intermittent AC charging disconnect",
    work_type: "EV systems",
    status: "scheduled",
    priority: "urgent",
  },
  {
    id: 8,
    text: "ADAS camera calibration",
    start_date: "2026-06-05 15:00",
    end_date: "2026-06-05 17:00",
    resource_id: "sofia",
    requester: "Ethan Clark",
    location: "Bay 8",
    asset: "2021 Honda Accord",
    issue: "Lane assist warning after windshield replacement",
    work_type: "Electrical calibration",
    status: "ready",
    priority: "normal",
  },
];
